-- Seed data for development. Idempotent (uses ON CONFLICT).

INSERT INTO sources (slug, name, organization, url, license, description) VALUES
  -- Chile
  ('sermig', 'Servicio Nacional de Migraciones', 'Servicio Nacional de Migraciones (SERMIG)', 'https://serviciomigraciones.cl', 'CC BY 4.0', 'Estadísticas oficiales de permanencias y residencias temporales/definitivas otorgadas en Chile.'),
  ('ine', 'Instituto Nacional de Estadísticas', 'INE Chile', 'https://www.ine.gob.cl', 'CC BY 4.0', 'Censo, encuestas de empleo, estimaciones intercensales y estadísticas de población.'),
  ('sii', 'Servicio de Impuestos Internos', 'SII', 'https://www.sii.cl', 'datos.gob.cl', 'Estadísticas de tributación: renta, IVA, contribuyentes activos.'),
  ('sp', 'Superintendencia de Pensiones', 'Superintendencia de Pensiones', 'https://www.spensiones.cl', 'CC BY 4.0', 'Cotizantes y afiliados al sistema de AFP por nacionalidad y región.'),
  ('mineduc', 'Ministerio de Educación', 'MINEDUC', 'https://datosabiertos.mineduc.cl', 'CC BY 4.0', 'Matrícula escolar y estadísticas educativas.'),
  ('sjm', 'Servicio Jesuita a Migrantes', 'SJM Chile', 'https://www.migracionenchile.cl', 'CC BY-NC 4.0', 'Estimaciones de migración irregular e informes anuales sobre migración en Chile.'),
  -- Venezuela / global
  ('world-bank', 'World Bank Open Data', 'Banco Mundial', 'https://data.worldbank.org/', 'CC BY 4.0', 'Indicadores macroeconómicos y de desarrollo consolidados de OMS, UNICEF, FMI, OIT y oficinas estadísticas nacionales. API JSON pública sin autenticación.'),
  ('freedom-house', 'Freedom in the World', 'Freedom House', 'https://freedomhouse.org/report/freedom-world', 'citada con atribución', 'Evaluación anual de derechos políticos y libertades civiles para 195 países. Score 0-100 + estatus F/PF/NF, publicado en febrero cada año.'),
  ('unhcr', 'UNHCR Population Statistics', 'Alto Comisionado de la ONU para los Refugiados (ACNUR)', 'https://www.unhcr.org/refugee-statistics/', 'CC BY 4.0', 'Refugiados, solicitantes de asilo y otros desplazados por país de origen y destino. Datos mensuales/anuales vía API JSON pública.'),
  ('unodc', 'UN Office on Drugs and Crime', 'UNODC', 'https://dataunodc.un.org/', 'CC BY 4.0', 'Estadísticas mundiales de homicidios intencionales por 100k habitantes. Consolidado por el Banco Mundial.'),
  ('mapa-olvido-base', 'Mapa del Olvido (datos comunitarios)', 'Cuentas Venezuela', 'https://cuentasvenezuela.org/mapa-del-olvido/metodologia', 'CC BY-SA 4.0', 'Catálogo abierto de obras públicas paralizadas, críticas o inoperativas en Venezuela. Compilado de informes oficiales, prensa y reportes ciudadanos. Cada obra cita su fuente primaria.')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  organization = EXCLUDED.organization,
  url = EXCLUDED.url,
  license = EXCLUDED.license,
  description = EXCLUDED.description;

INSERT INTO datasets (slug, source_id, title, description, parquet_key, extracted_at) VALUES
  ('sermig-stock-region',  (SELECT id FROM sources WHERE slug='sermig'),  'Stock migratorio venezolano por región',  'Permanencias vigentes por región y año',  'sermig/stock_region.parquet',  NOW()),
  ('sermig-stock-comuna',  (SELECT id FROM sources WHERE slug='sermig'),  'Stock migratorio venezolano por comuna', 'Permanencias vigentes por comuna y año',  'sermig/stock_comuna.parquet', NOW()),
  ('ine-empleo-nacionalidad',  (SELECT id FROM sources WHERE slug='ine'),  'Empleo por nacionalidad', 'Tasa de ocupación, formal/informal, por nacionalidad', 'ine/empleo_nacionalidad.parquet', NOW()),
  ('sp-cotizantes',  (SELECT id FROM sources WHERE slug='sp'),  'Cotizantes AFP por nacionalidad y sector', 'Serie mensual de cotizantes activos', 'sp/cotizantes.parquet', NOW()),
  ('sii-aporte-tributario',  (SELECT id FROM sources WHERE slug='sii'),  'Aporte tributario estimado', 'Aporte de impuesto a la renta e IVA estimado', 'sii/aporte.parquet', NOW()),
  ('mineduc-matricula',  (SELECT id FROM sources WHERE slug='mineduc'),  'Matrícula escolar venezolana', 'Estudiantes matriculados por región', 'mineduc/matricula.parquet', NOW()),
  ('sjm-irregularidad',  (SELECT id FROM sources WHERE slug='sjm'),  'Estimación de irregularidad', 'Estimación anual de migración irregular', 'sjm/irregularidad.parquet', NOW()),
  -- Venezuela / global
  ('wb-ve-macro',        (SELECT id FROM sources WHERE slug='world-bank'),    'World Bank indicators — Venezuela + Chile', '29 indicadores macroeconómicos y sociales (PIB, esperanza vida, mortalidad, internet, electricidad, etc) para VEN y CHL, 1998-presente', 'macro_ve/wb_indicators.parquet', NOW()),
  ('fh-freedom-world',   (SELECT id FROM sources WHERE slug='freedom-house'), 'Freedom in the World scores', 'Score combinado (PR + CL) + estatus F/PF/NF para 12 países LATAM, 2013-presente', 'ddhh/freedom_house.parquet', NOW()),
  ('unhcr-ve-diaspora',  (SELECT id FROM sources WHERE slug='unhcr'),         'Diáspora venezolana por país de destino', 'Refugiados + solicitantes de asilo + otros desplazados por país de destino (COA), 2010-presente', 'migracion/acnur_ve.parquet', NOW()),
  ('obras-ve',           (SELECT id FROM sources WHERE slug='mapa-olvido-base'), 'Obras públicas paralizadas — Venezuela', 'Catálogo de obras inauguradas, paralizadas, críticas o inoperativas en VE. Geolocalizadas con presupuesto, estatus y fuente primaria.', 'obras/obras.parquet', NOW())
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  parquet_key = EXCLUDED.parquet_key,
  extracted_at = EXCLUDED.extracted_at;

INSERT INTO indicators (slug, name, category, unit, description, dataset_id) VALUES
  ('stock-legal-region',     'Stock legal por región',          'Demografía', 'personas',     'Permanencias vigentes por región',                       (SELECT id FROM datasets WHERE slug='sermig-stock-region')),
  ('stock-legal-comuna',     'Stock legal por comuna',          'Demografía', 'personas',     'Permanencias vigentes por comuna',                       (SELECT id FROM datasets WHERE slug='sermig-stock-comuna')),
  ('estimado-irregular',     'Estimación de irregularidad',      'Demografía', 'personas',     'Estimación de migración irregular (SJM)',                (SELECT id FROM datasets WHERE slug='sjm-irregularidad')),
  ('tasa-ocupacion',         'Tasa de ocupación',                'Trabajo',    'porcentaje',   'Porcentaje de ocupados sobre PEA migrante',              (SELECT id FROM datasets WHERE slug='ine-empleo-nacionalidad')),
  ('tasa-formalidad',        'Tasa de formalidad laboral',       'Trabajo',    'porcentaje',   'Porcentaje de empleo con contrato formal',               (SELECT id FROM datasets WHERE slug='ine-empleo-nacionalidad')),
  ('cotizantes-afp',         'Cotizantes AFP',                   'Pensiones', 'personas',      'Cotizantes activos en el sistema AFP',                   (SELECT id FROM datasets WHERE slug='sp-cotizantes')),
  ('cotizantes-sector',      'Cotizantes por sector',            'Pensiones', 'personas',      'Distribución de cotizantes por sector económico',        (SELECT id FROM datasets WHERE slug='sp-cotizantes')),
  ('aporte-renta',           'Aporte impuesto a la renta',       'Tributario','CLP',           'Aporte estimado por impuesto a la renta',                (SELECT id FROM datasets WHERE slug='sii-aporte-tributario')),
  ('aporte-iva',             'Aporte IVA',                       'Tributario','CLP',           'Aporte estimado por IVA',                                (SELECT id FROM datasets WHERE slug='sii-aporte-tributario')),
  ('matricula-escolar',      'Matrícula escolar',                'Educación', 'estudiantes',   'Estudiantes venezolanos matriculados',                   (SELECT id FROM datasets WHERE slug='mineduc-matricula')),
  -- Venezuela / global indicators (high-level pointers; full breakdown lives in macro_ve.wb_indicators)
  ('ve-pib-pc',              'PIB per cápita (Venezuela vs Chile)','Economía',  'USD',          'Indicador WB NY.GDP.PCAP.CD para VEN y CHL',             (SELECT id FROM datasets WHERE slug='wb-ve-macro')),
  ('ve-inflacion',           'Inflación IPC anual',              'Economía',  'porcentaje',    'Indicador WB FP.CPI.TOTL.ZG',                            (SELECT id FROM datasets WHERE slug='wb-ve-macro')),
  ('ve-esperanza-vida',      'Esperanza de vida al nacer',       'Salud',     'años',          'Indicador WB SP.DYN.LE00.IN',                            (SELECT id FROM datasets WHERE slug='wb-ve-macro')),
  ('ve-mortalidad-infantil', 'Mortalidad infantil (<1 año)',     'Salud',     'por mil n.v.',  'Indicador WB SP.DYN.IMRT.IN',                            (SELECT id FROM datasets WHERE slug='wb-ve-macro')),
  ('ve-homicidios',          'Homicidios intencionales',         'Inseguridad','por 100k',     'Indicador WB VC.IHR.PSRC.P5 (fuente UNODC)',             (SELECT id FROM datasets WHERE slug='wb-ve-macro')),
  ('ve-freedom-total',       'Freedom House — Score total',      'DDHH',      'puntos (0-100)','Score combinado PR+CL de Freedom House',                 (SELECT id FROM datasets WHERE slug='fh-freedom-world')),
  ('ve-freedom-status',      'Freedom House — Estatus',          'DDHH',      'F/PF/NF',       'Clasificación cualitativa Free / Partly Free / Not Free',(SELECT id FROM datasets WHERE slug='fh-freedom-world')),
  ('ve-diaspora-refugees',   'Refugiados venezolanos por destino','Migración','personas',      'Refugiados venezolanos reconocidos por país de destino', (SELECT id FROM datasets WHERE slug='unhcr-ve-diaspora')),
  ('ve-diaspora-asylum',     'Solicitantes de asilo venezolanos','Migración','personas',       'Solicitantes de asilo pendientes por país de destino',   (SELECT id FROM datasets WHERE slug='unhcr-ve-diaspora')),
  ('ve-obras-paralizadas',   'Obras públicas paralizadas',       'Infraestructura','obras',    'Obras inauguradas, paralizadas, críticas o inoperativas',(SELECT id FROM datasets WHERE slug='obras-ve'))
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  description = EXCLUDED.description,
  dataset_id = EXCLUDED.dataset_id;

-- ===== Mapa del Olvido: seed obras (mirror of mapa-olvido-vnzla scraper/seed.py) =====
INSERT INTO obras (
  id, nombre, lat, lng, geohash, presupuesto_usd, anio_inicio, categoria,
  estado_venezuela, estatus, ente_responsable, fuente_url, fotos_url,
  descripcion, progreso_pct, sobrecosto_pct, presupuesto_original_usd,
  responsable_politico, partido_politico, contratista
) VALUES
  ('hospital-maracaibo', 'Hospital Universitario de Maracaibo',
   10.651, -71.614, 'e6ku4p',
   45000000, 2003, 'Salud',
   'Zulia', 'paralizada', 'MPPS',
   'https://transparenciave.org/obras/1', '[]'::jsonb,
   'Centro de atención médica de alta complejidad anunciado para descongestionar el Hospital Central. Tras 22 años, las estructuras están abandonadas y vandalizadas.',
   35, 180, 16000000,
   'Manuel Rosales', 'Un Nuevo Tiempo', 'Constructora Norberto Odebrecht'),

  ('viaducto-la-cabrera', 'Viaducto La Cabrera',
   10.327, -66.104, 'djvqkp',
   120000000, 2007, 'Infraestructura',
   'Miranda', 'critica', 'MINFRA',
   'https://transparenciave.org/obras/2', '[]'::jsonb,
   'Conexión vial estratégica entre Caracas y los Valles del Tuy. Estructura presenta fallas geológicas sin resolver.',
   78, 95, 61500000,
   'Diosdado Cabello', 'PSUV', 'Odebrecht Venezuela'),

  ('estadio-puerto-la-cruz', 'Estadio de Béisbol Puerto La Cruz',
   10.213, -64.638, 'dju8kp',
   18000000, 2011, 'Deporte',
   'Anzoátegui', 'inoperativa', 'MPPE',
   'https://transparenciave.org/obras/3', '[]'::jsonb,
   'Estadio anunciado para Serie del Caribe 2014. Inaugurado parcialmente, hoy sin uso por daños estructurales.',
   90, 50, 12000000,
   'Tarek William Saab', 'PSUV', 'Constructora del Caribe'),

  ('linea5-metro-caracas', 'Línea 5 Metro de Caracas',
   10.491, -66.878, 'djv0kp',
   890000000, 1999, 'Transporte',
   'Distrito Capital', 'paralizada', 'Metro de Caracas',
   'https://transparenciave.org/obras/4', '[]'::jsonb,
   'Línea anunciada hace 26 años para conectar Plaza Venezuela con Parque del Este. Túneles excavados parcialmente, sin estaciones funcionales.',
   22, 245, 258000000,
   'Hugo Chávez Frías', 'MVR / PSUV', 'Consorcio Constructora Norberto Odebrecht-Ghella'),

  ('universidad-tachira', 'Universidad Bolivariana del Táchira',
   7.773, -72.226, 'd39jkp',
   25000000, 2014, 'Educación',
   'Táchira', 'critica', 'MPPES',
   'https://transparenciave.org/obras/5', '[]'::jsonb,
   'Sede universitaria anunciada con capacidad para 8.000 estudiantes. Edificios sin terminar, sin servicios básicos.',
   55, 30, 19200000,
   'José Vielma Mora', 'PSUV', 'Sin licitación pública'),

  ('central-tocoma', 'Central Hidroeléctrica Tocoma',
   7.892, -63.103, 'd6vk7p',
   4300000000, 2007, 'Energía',
   'Bolívar', 'paralizada', 'CORPOELEC',
   'https://transparenciave.org/obras/6', '[]'::jsonb,
   'Central hidroeléctrica anunciada con capacidad de 2.160 MW. Tras 18 años, opera al 40% de capacidad por fallas en turbinas.',
   60, 110, 2050000000,
   'Hugo Chávez Frías', 'PSUV', 'Constructora OAS'),

  -- Más obras documentadas (proyectos públicos ampliamente reportados).
  ('puente-nigale-zulia', 'Segundo Puente sobre el Lago de Maracaibo (Nigale)',
   10.638, -71.620, 'e6ku3p',
   1800000000, 2006, 'Infraestructura',
   'Zulia', 'paralizada', 'MPPTOP',
   'https://transparenciave.org/obras/nigale', '[]'::jsonb,
   'Segundo puente sobre el Lago de Maracaibo anunciado en 2006 con China para descongestionar el Rafael Urdaneta. Estudios técnicos completados, obra física nunca inició.',
   5, 0, 1500000000,
   'Hugo Chávez Frías', 'PSUV', 'CITIC Construction (anunciado)'),

  ('refineria-cabruta', 'Refinería Cabruta',
   7.642, -66.250, 'd5z8kp',
   12000000000, 2007, 'Energía',
   'Guárico', 'inoperativa', 'PDVSA',
   'https://transparenciave.org/obras/cabruta', '[]'::jsonb,
   'Refinería de 400.000 b/d anunciada en convenio con Brasil. Tras casi dos décadas sin construcción. Una de las anuncios fallidos más grandes del sector petrolero.',
   2, 0, 8500000000,
   'Hugo Chávez Frías', 'PSUV', 'Petrobras (acuerdo cancelado)'),

  ('sistema-yacambu-quibor', 'Sistema Hidráulico Yacambú-Quibor',
   9.515, -69.674, 'd6m2kp',
   1500000000, 1976, 'Infraestructura',
   'Lara', 'critica', 'MINEC',
   'https://transparenciave.org/obras/yacambu', '[]'::jsonb,
   'Trasvase para regar el valle de Quibor anunciado en 1973. Túnel concluido en 2014 tras 38 años; sistema de distribución sigue incompleto medio siglo después.',
   65, 320, 350000000,
   'Carlos Andrés Pérez', 'AD', 'múltiples contratistas'),

  ('linea-4-metro-caracas', 'Línea 4 Metro de Caracas',
   10.501, -66.892, 'djv1kp',
   650000000, 2002, 'Transporte',
   'Distrito Capital', 'critica', 'Metro de Caracas',
   'https://transparenciave.org/obras/linea4', '[]'::jsonb,
   'Extensión Capuchinos-Zona Rental anunciada para 2007. Operativa solo entre Capuchinos y Plaza Venezuela; resto sin terminar.',
   45, 80, 360000000,
   'Hugo Chávez Frías', 'MVR', 'Constructora Norberto Odebrecht'),

  ('tren-caracas-cua', 'Tren Caracas - Charallave - Cúa (extensión Norte)',
   10.213, -66.881, 'djuvkp',
   2200000000, 2006, 'Transporte',
   'Miranda', 'critica', 'IFE',
   'https://transparenciave.org/obras/tren-cua', '[]'::jsonb,
   'Sistema ferroviario operativo en tramo Caracas-Charallave. Extensiones anunciadas hacia Guatire y Norte capital sin avance significativo.',
   55, 60, 1370000000,
   'Hugo Chávez Frías', 'MVR / PSUV', 'Consorcio Sismetro'),

  ('hospital-cardiologico-infantil', 'Hospital Cardiológico Infantil Latinoamericano',
   10.523, -66.913, 'djv4kp',
   85000000, 2006, 'Salud',
   'Distrito Capital', 'critica', 'MPPS',
   'https://transparenciave.org/obras/cardio-infantil', '[]'::jsonb,
   'Inaugurado en 2006 como hospital cardiológico pediátrico. Funciona pero con equipamiento envejecido y crisis de insumos; pacientes derivados a otros centros desde 2017.',
   95, 25, 68000000,
   'Hugo Chávez Frías', 'MVR / PSUV', 'AKAR Constructora'),

  ('tren-tinaco-anaco', 'Sistema Ferroviario Tinaco - Anaco',
   8.880, -65.426, 'd6h1kp',
   7600000000, 2005, 'Transporte',
   'Anzoátegui', 'inoperativa', 'IFE',
   'https://transparenciave.org/obras/tinaco-anaco', '[]'::jsonb,
   'Línea férrea de 471 km anunciada con financiación China-Venezuela. Más de 18 años después, vía nunca completada; vagones almacenados sin uso.',
   12, 50, 5100000000,
   'Hugo Chávez Frías', 'PSUV', 'CRRC + UCOCAR'),

  ('aeropuerto-internacional-maturin', 'Aeropuerto Internacional José Tadeo Monagas (renovación)',
   9.748, -63.148, 'd6r8kp',
   180000000, 2010, 'Infraestructura',
   'Monagas', 'critica', 'INAC',
   'https://transparenciave.org/obras/aeropuerto-maturin', '[]'::jsonb,
   'Ampliación y modernización del aeropuerto. Obras pausadas desde 2015; pista y terminal sin completar.',
   55, 70, 105000000,
   'Hugo Chávez Frías', 'PSUV', 'Constructora Camargo Corrêa'),

  ('puerto-altagracia-orinoco', 'Puerto de Altagracia de Orinoco (expansión)',
   8.595, -62.430, 'd6n4kp',
   430000000, 2008, 'Infraestructura',
   'Bolívar', 'inoperativa', 'MPPTOP',
   'https://transparenciave.org/obras/puerto-orinoco', '[]'::jsonb,
   'Expansión del puerto fluvial para exportación de mineral de hierro. Equipamiento adquirido nunca instalado; muelles deteriorados.',
   30, 90, 226000000,
   'Hugo Chávez Frías', 'PSUV', 'CVG Ferrominera'),

  ('estadio-olimpico-ucv', 'Estadio Olímpico UCV (renovación Copa América 2007)',
   10.493, -66.890, 'djv2kp',
   45000000, 2005, 'Deporte',
   'Distrito Capital', 'critica', 'IND',
   'https://transparenciave.org/obras/olimpico-ucv', '[]'::jsonb,
   'Renovación para Copa América 2007. Concluido parcialmente; instalaciones se deterioraron sin mantenimiento desde 2014.',
   75, 50, 30000000,
   'Hugo Chávez Frías', 'MVR / PSUV', 'IND + contratistas locales'),

  ('vivienda-ezequiel-zamora-caracas', 'Gran Misión Vivienda — Macrocomplejo Ezequiel Zamora',
   10.467, -66.918, 'djv5kp',
   320000000, 2011, 'Vivienda',
   'Distrito Capital', 'critica', 'MINHVI',
   'https://transparenciave.org/obras/misionvivienda-ezequiel-zamora', '[]'::jsonb,
   'Complejo habitacional de 7.000 viviendas. Entregadas algunas torres; el resto sin servicios básicos (agua, electricidad estable, ascensores).',
   60, 40, 230000000,
   'Hugo Chávez Frías', 'PSUV', 'consorcios bolivarianos'),

  ('refineria-caripito', 'Reactivación Refinería de Caripito',
   10.122, -63.097, 'd71nkp',
   500000000, 2011, 'Energía',
   'Monagas', 'inoperativa', 'PDVSA',
   'https://transparenciave.org/obras/caripito', '[]'::jsonb,
   'Reactivación de refinería histórica cerrada en 1975. Anuncio nunca cristalizó; planta sigue desmantelada.',
   8, 0, 380000000,
   'Hugo Chávez Frías', 'PSUV', 'PDVSA (sin contratista externo)'),

  ('central-termoelectrica-josefa-camejo', 'Central Termoeléctrica Josefa Camejo',
   11.704, -70.179, 'eebjkp',
   860000000, 2008, 'Energía',
   'Falcón', 'critica', 'CORPOELEC',
   'https://transparenciave.org/obras/josefa-camejo', '[]'::jsonb,
   'Planta termoeléctrica de 470 MW. Opera a fracción de capacidad nominal por falta de mantenimiento de turbinas y suministro irregular de gas.',
   70, 80, 480000000,
   'Hugo Chávez Frías', 'PSUV', 'Industrias Tecno'),

  ('puerto-libre-paraguana', 'Puerto Libre de Paraguaná (zona económica especial)',
   11.917, -69.965, 'ee9zkp',
   240000000, 2014, 'Infraestructura',
   'Falcón', 'inoperativa', 'MPPC',
   'https://transparenciave.org/obras/paraguana', '[]'::jsonb,
   'Zona económica especial y puerto libre anunciados para reactivar comercio. Infraestructura aduanal y vial sin completar; operación nominal.',
   25, 0, 240000000,
   'Nicolás Maduro', 'PSUV', 'CVG + privados'),

  ('hospital-cardiologico-maracay', 'Hospital Cardiológico Adulto de Maracay',
   10.249, -67.598, 'djr8kp',
   95000000, 2010, 'Salud',
   'Aragua', 'critica', 'MPPS',
   'https://transparenciave.org/obras/cardio-maracay', '[]'::jsonb,
   'Centro cardiológico para adultos anunciado en 2010. Estructura levantada parcialmente; sin equipos médicos instalados.',
   45, 30, 72000000,
   'Tareck El Aissami', 'PSUV', 'Inversora Avanti'),

  -- Históricas adicionales (1999-2024) por categoría / estado.
  -- Transporte
  ('metrocable-mariche', 'Metro Cable Mariche', 10.500, -66.811, 'djv6kp',
   140000000, 2010, 'Transporte', 'Miranda', 'paralizada', 'Metro de Caracas',
   'https://transparenciave.org/obras/metrocable-mariche', '[]'::jsonb,
   'Sistema teleférico para San Agustín, Mariche y El Valle. Solo se completó el de San Agustín; los otros dos ramales paralizados.',
   30, 60, 90000000, 'Hugo Chávez Frías', 'PSUV', 'POMA / DOPPELMAYR'),
  ('trolmerida-fase2', 'Trolmérida — Fase 2 (Mucujún)', 8.589, -71.140, 'd66skp',
   220000000, 2007, 'Transporte', 'Mérida', 'critica', 'TROMERCA',
   'https://transparenciave.org/obras/trolmerida-fase2', '[]'::jsonb,
   'Extensión del sistema trolebús hasta Mucujún. Vehículos adquiridos en 2007 nunca entraron en operación; ruta inconclusa.',
   40, 80, 130000000, 'Hugo Chávez Frías', 'PSUV', 'Mercedes-Benz / TROMERCA'),
  ('metro-valencia', 'Metro de Valencia (líneas 2 y 3)', 10.176, -68.005, 'd6r1kp',
   1400000000, 2006, 'Transporte', 'Carabobo', 'critica', 'MetroValencia',
   'https://transparenciave.org/obras/metro-valencia', '[]'::jsonb,
   'Sistema metro operativo en línea 1 corta. Líneas 2 y 3 anunciadas sin avance significativo desde 2012.',
   25, 110, 700000000, 'Henrique Fernando Salas', 'PSUV', 'Consorcio Sismetro'),
  ('metro-maracaibo', 'Metro de Maracaibo (extensiones)', 10.653, -71.640, 'e6ku1p',
   980000000, 2006, 'Transporte', 'Zulia', 'critica', 'MetroMARACAIBO',
   'https://transparenciave.org/obras/metro-maracaibo', '[]'::jsonb,
   'Línea 1 operativa Altos de la Vanega-Sabaneta. Extensiones a Costa Norte anunciadas, sin construcción.',
   35, 80, 540000000, 'Hugo Chávez Frías', 'PSUV', 'Sermesa'),
  ('tren-norte-llanero', 'Tren Norte Llanero (Anaco-Tucupita)', 9.300, -63.500, 'd6t5kp',
   3200000000, 2008, 'Transporte', 'Anzoátegui', 'inoperativa', 'IFE',
   'https://transparenciave.org/obras/tren-norte-llanero', '[]'::jsonb,
   'Sistema férreo de 558 km. Equipos chinos comprados; vías nunca tendidas más allá de tramos piloto.',
   8, 0, 2900000000, 'Hugo Chávez Frías', 'PSUV', 'CRRC + IFE'),
  ('aeropuerto-la-chinita', 'Aeropuerto Internacional La Chinita (renovación)', 10.558, -71.728, 'e6kh2p',
   240000000, 2012, 'Infraestructura', 'Zulia', 'critica', 'INAC',
   'https://transparenciave.org/obras/la-chinita', '[]'::jsonb,
   'Modernización terminal + pista. Obras inconclusas; algunas áreas en uso, otras cerradas por falta de mantenimiento.',
   60, 50, 160000000, 'Francisco Arias Cárdenas', 'PSUV', 'INAC + contratistas locales'),

  -- Energía
  ('termocarabobo', 'Planta Termoeléctrica Termocarabobo', 10.175, -67.998, 'd6rckp',
   1700000000, 2009, 'Energía', 'Carabobo', 'critica', 'CORPOELEC',
   'https://transparenciave.org/obras/termocarabobo', '[]'::jsonb,
   'Planta de 990 MW. Opera muy por debajo de su capacidad por falta de mantenimiento y suministro de gas.',
   75, 90, 920000000, 'Hugo Chávez Frías', 'PSUV', 'Industrias Tecno'),
  ('termocentro-tinaquillo', 'Termoeléctrica Centro (Tinaquillo)', 9.917, -68.290, 'd6m9kp',
   1300000000, 2010, 'Energía', 'Cojedes', 'critica', 'CORPOELEC',
   'https://transparenciave.org/obras/termocentro', '[]'::jsonb,
   'Planta de 660 MW. Comisionada parcialmente; varias unidades fuera de servicio por años.',
   65, 70, 760000000, 'Hugo Chávez Frías', 'PSUV', 'Mitsubishi / Caracas Mining'),
  ('termoaragua', 'Termoeléctrica Termoaragua', 10.270, -67.470, 'djrjkp',
   850000000, 2008, 'Energía', 'Aragua', 'inoperativa', 'CORPOELEC',
   'https://transparenciave.org/obras/termoaragua', '[]'::jsonb,
   'Anunciada para 420 MW. Unidades llegaron al país pero quedaron sin instalar; sin operación reportada.',
   20, 50, 560000000, 'Hugo Chávez Frías', 'PSUV', 'Skoda Praha'),
  ('refineria-el-palito', 'Refinería El Palito (modernización)', 10.487, -68.243, 'd6r0kp',
   2400000000, 2008, 'Energía', 'Carabobo', 'critica', 'PDVSA',
   'https://transparenciave.org/obras/el-palito', '[]'::jsonb,
   'Programa de modernización. Opera a 30% de capacidad nominal desde 2018 por fallas crónicas y falta de inversión.',
   55, 60, 1500000000, 'Hugo Chávez Frías', 'PSUV', 'PDVSA + contratistas'),
  ('refineria-amuay-cardon', 'Complejo Refinador Paraguaná (Amuay+Cardón rehabilitación)', 11.770, -70.215, 'eebd5p',
   5800000000, 2013, 'Energía', 'Falcón', 'critica', 'PDVSA',
   'https://transparenciave.org/obras/paraguana', '[]'::jsonb,
   'Mayor complejo refinador del país. Tras explosión Amuay 2012, programa de rehabilitación con avances muy parciales; opera a fracción de su capacidad histórica.',
   45, 130, 2500000000, 'Nicolás Maduro', 'PSUV', 'PDVSA'),

  -- Vivienda (Gran Misión Vivienda Venezuela)
  ('vivienda-hugo-chavez-eterno', 'Macrocomplejo Hugo Chávez Eterno', 10.460, -66.880, 'djv7kp',
   480000000, 2013, 'Vivienda', 'Distrito Capital', 'critica', 'MINHVI',
   'https://transparenciave.org/obras/gmvv-hcheterno', '[]'::jsonb,
   '10.000 viviendas anunciadas. Estructura levantada; problemas crónicos de agua, ascensores y mantenimiento desde entrega.',
   80, 30, 370000000, 'Nicolás Maduro', 'PSUV', 'consorcios bolivarianos'),
  ('vivienda-ciudad-tiuna', 'Ciudad Tiuna (Fuerte Tiuna habitacional)', 10.450, -66.927, 'djv9kp',
   620000000, 2011, 'Vivienda', 'Distrito Capital', 'critica', 'MINHVI',
   'https://transparenciave.org/obras/ciudad-tiuna', '[]'::jsonb,
   'Complejo de 15.000 viviendas dentro del Fuerte Tiuna. Solo fracción terminada; sectores sin servicios.',
   55, 40, 440000000, 'Hugo Chávez Frías', 'PSUV', 'MINHVI'),
  ('vivienda-poliedro-maracay', 'Macrocomplejo Poliedro de Maracay', 10.240, -67.610, 'djr3kp',
   180000000, 2012, 'Vivienda', 'Aragua', 'critica', 'MINHVI',
   'https://transparenciave.org/obras/gmvv-poliedro-maracay', '[]'::jsonb,
   'Edificios habitacionales en zona del Poliedro. Algunas torres ocupadas, otras inconclusas con vandalismo.',
   65, 25, 140000000, 'Tareck El Aissami', 'PSUV', 'consorcios'),

  -- Salud
  ('hospital-jm-rios', 'J.M. de los Ríos — modernización', 10.498, -66.879, 'djv8kp',
   65000000, 2008, 'Salud', 'Distrito Capital', 'critica', 'MPPS',
   'https://transparenciave.org/obras/jmrios', '[]'::jsonb,
   'Hospital pediátrico nacional. Programa de renovación anunciado en 2008 nunca completado; equipos y áreas críticas con fallas crónicas.',
   40, 50, 42000000, 'Hugo Chávez Frías', 'PSUV', 'sin licitación pública'),
  ('hospital-vargas', 'Hospital Vargas de Caracas (renovación)', 10.510, -66.910, 'djv4kp',
   55000000, 2010, 'Salud', 'Distrito Capital', 'critica', 'MPPS',
   'https://transparenciave.org/obras/vargas', '[]'::jsonb,
   'Hospital histórico (1888). Plan de modernización con avances parciales; pabellones con fallas estructurales por años.',
   45, 40, 38000000, 'Hugo Chávez Frías', 'PSUV', 'MPPS + contratistas'),
  ('hospital-razetti', 'Hospital Luis Razetti (Anzoátegui)', 10.137, -64.680, 'd6u4kp',
   38000000, 2009, 'Salud', 'Anzoátegui', 'critica', 'MPPS',
   'https://transparenciave.org/obras/razetti', '[]'::jsonb,
   'Hospital central de Anzoátegui. Modernización anunciada nunca concluida; áreas cerradas por colapso estructural.',
   55, 35, 27000000, 'Tarek William Saab', 'PSUV', 'MPPS regional'),
  ('hospital-domingo-luciani', 'Hospital Dr. Domingo Luciani (El Llanito)', 10.473, -66.815, 'djv0kp',
   72000000, 2007, 'Salud', 'Miranda', 'critica', 'MPPS',
   'https://transparenciave.org/obras/domingo-luciani', '[]'::jsonb,
   'Hospital de referencia. Programa de equipamiento y mantenimiento incompleto; servicios reducidos.',
   50, 50, 48000000, 'Hugo Chávez Frías', 'PSUV', 'MPPS'),
  ('hospital-pediatrico-pastor-oropeza', 'Hospital Pediátrico Dr. Pastor Oropeza (Barquisimeto)', 10.064, -69.353, 'd6m9kp',
   42000000, 2011, 'Salud', 'Lara', 'critica', 'MPPS',
   'https://transparenciave.org/obras/pastor-oropeza', '[]'::jsonb,
   'Hospital pediátrico regional. Mantenimiento histórico deficiente; varias áreas inoperativas desde 2017.',
   60, 30, 32000000, 'Henri Falcón', 'PSUV', 'MPPS regional'),

  -- Educación
  ('upel-instituto-pedagogico-barquisimeto', 'UPEL — IPB Barquisimeto (ampliación)', 10.064, -69.366, 'd6m8kp',
   28000000, 2007, 'Educación', 'Lara', 'critica', 'UPEL',
   'https://transparenciave.org/obras/upel-ipb', '[]'::jsonb,
   'Ampliación del Instituto Pedagógico de Barquisimeto. Obras paralizadas desde 2014 por falta de presupuesto.',
   50, 40, 20000000, 'Hugo Chávez Frías', 'PSUV', 'UPEL + contratistas'),
  ('unearte-sede-nacional', 'Universidad de las Artes — Sede Nacional', 10.498, -66.900, 'djv5kp',
   34000000, 2008, 'Educación', 'Distrito Capital', 'critica', 'UNEARTE',
   'https://transparenciave.org/obras/unearte', '[]'::jsonb,
   'Sede nacional UNEARTE en Caracas. Instalaciones operativas pero con áreas cerradas y problemas de mantenimiento.',
   70, 20, 28000000, 'Hugo Chávez Frías', 'PSUV', 'UNEARTE'),
  ('universidad-deportiva-sur', 'Universidad Iberoamericana del Deporte (Cojedes)', 9.650, -68.580, 'd6mqkp',
   85000000, 2007, 'Educación', 'Cojedes', 'inoperativa', 'IUD',
   'https://transparenciave.org/obras/iud-deporte', '[]'::jsonb,
   'Universidad anunciada para formar atletas profesionales. Estructura levantada parcialmente; sin matrícula activa significativa.',
   30, 60, 50000000, 'Hugo Chávez Frías', 'PSUV', 'IUD + contratistas'),

  -- Infraestructura vial
  ('distribuidor-petare', 'Distribuidor Vial Petare (ampliación)', 10.480, -66.811, 'djv2kp',
   180000000, 2009, 'Infraestructura', 'Miranda', 'critica', 'MPPTOP',
   'https://transparenciave.org/obras/distribuidor-petare', '[]'::jsonb,
   'Sistema de elevados y rampas para descongestionar Petare. Construcción parcial; fases incompletas con tramos inconclusos.',
   55, 40, 125000000, 'Hugo Chávez Frías', 'PSUV', 'Consorcio Vial Bolivariano'),
  ('autopista-caracas-la-guaira', 'Autopista Caracas-La Guaira (Viaducto + mantenimiento)', 10.575, -67.060, 'djtfkp',
   850000000, 2007, 'Infraestructura', 'Vargas', 'critica', 'MPPTOP',
   'https://transparenciave.org/obras/aclg', '[]'::jsonb,
   'Reemplazo del Viaducto 1 ejecutado 2006-2008. Programa de mantenimiento posterior incompleto; sectores con deterioro estructural.',
   80, 35, 630000000, 'Hugo Chávez Frías', 'PSUV', 'Odebrecht'),
  ('autopista-jose-antonio-paez', 'Autopista José Antonio Páez (rehabilitación)', 8.626, -70.210, 'd5n5kp',
   220000000, 2010, 'Infraestructura', 'Barinas', 'critica', 'MPPTOP',
   'https://transparenciave.org/obras/ajap', '[]'::jsonb,
   'Vía estratégica Caracas-llanos. Rehabilitaciones inconclusas; varios tramos con pavimento deficiente y puentes con fallas.',
   50, 50, 145000000, 'Adán Chávez', 'PSUV', 'Consorcio Vial'),

  -- Agua y saneamiento
  ('acueducto-tuy-iv', 'Sistema Tuy IV (acueducto Caracas)', 10.250, -66.870, 'djs4kp',
   1700000000, 2008, 'Infraestructura', 'Miranda', 'critica', 'HIDROCAPITAL',
   'https://transparenciave.org/obras/tuy-iv', '[]'::jsonb,
   'Cuarto sistema de aducción para Caracas. Avances parciales por 16 años; suministro intermitente persiste en muchos sectores.',
   55, 90, 900000000, 'Hugo Chávez Frías', 'PSUV', 'HIDROCAPITAL + contratistas'),
  ('embalse-tarra', 'Embalse Río Tarra', 7.770, -72.140, 'd39mkp',
   320000000, 2010, 'Infraestructura', 'Táchira', 'paralizada', 'MINEC',
   'https://transparenciave.org/obras/embalse-tarra', '[]'::jsonb,
   'Embalse para riego y abastecimiento. Obras paralizadas desde 2014; presa parcialmente levantada sin compuertas operativas.',
   35, 75, 180000000, 'José Vielma Mora', 'PSUV', 'MINEC + contratistas'),
  ('planta-tratamiento-mariposa', 'Planta de Tratamiento La Mariposa', 10.440, -66.952, 'djv3kp',
   95000000, 2009, 'Infraestructura', 'Distrito Capital', 'critica', 'HIDROCAPITAL',
   'https://transparenciave.org/obras/mariposa', '[]'::jsonb,
   'Tratamiento de agua para Caracas. Modernización anunciada con avances parciales; capacidad efectiva inferior a la nominal.',
   60, 35, 70000000, 'Hugo Chávez Frías', 'PSUV', 'HIDROCAPITAL'),

  -- Deporte
  ('estadio-monumental-margarita', 'Estadio Monumental de Margarita', 11.000, -63.860, 'eeb7kp',
   38000000, 2008, 'Deporte', 'Nueva Esparta', 'critica', 'IND',
   'https://transparenciave.org/obras/monumental-margarita', '[]'::jsonb,
   'Estadio de béisbol para 18.000 espectadores. Inaugurado parcialmente; sin uso regular por mantenimiento deficiente.',
   80, 40, 27000000, 'Morel Rodríguez', 'PSUV', 'IND + contratistas'),
  ('polideportivo-misael-delgado', 'Polideportivo Misael Delgado (Valencia)', 10.181, -68.000, 'd6r1kp',
   18000000, 2007, 'Deporte', 'Carabobo', 'critica', 'IND',
   'https://transparenciave.org/obras/misael-delgado', '[]'::jsonb,
   'Complejo deportivo regional. Renovación incompleta; piscina, gimnasio y áreas comunes con cierres parciales.',
   65, 30, 13000000, 'Henrique Fernando Salas', 'PSUV', 'IND regional'),
  ('estadio-jesus-aristimuno', 'Estadio Jesús Aristimuño (Maracay) renovación', 10.247, -67.601, 'djr0kp',
   12000000, 2012, 'Deporte', 'Aragua', 'critica', 'IND',
   'https://transparenciave.org/obras/aristimuno', '[]'::jsonb,
   'Renovación del estadio. Trabajos parciales; gradas e iluminación con deficiencias persistentes.',
   55, 35, 8500000, 'Tareck El Aissami', 'PSUV', 'IND regional'),

  -- Industria / Agroindustria
  ('empresa-mixta-cemento', 'Empresa Mixta Cementera Cerro Azul', 10.220, -69.330, 'd6m6kp',
   240000000, 2009, 'Industria', 'Lara', 'critica', 'MPPI',
   'https://transparenciave.org/obras/cerro-azul', '[]'::jsonb,
   'Cementera estatal-china. Capacidad nominal de 1M ton/año; opera a fracción mínima desde 2017.',
   60, 60, 150000000, 'Hugo Chávez Frías', 'PSUV', 'CITIC / MPPI'),
  ('planta-procesadora-leche-machiques', 'Planta procesadora de leche Machiques', 10.064, -72.555, 'd9hxkp',
   42000000, 2008, 'Industria', 'Zulia', 'inoperativa', 'CVAL',
   'https://transparenciave.org/obras/lacteos-machiques', '[]'::jsonb,
   'Planta estatal de lácteos. Equipos importados nunca puestos en operación regular; cierre técnico desde 2016.',
   25, 50, 28000000, 'Hugo Chávez Frías', 'PSUV', 'CVAL'),
  ('agropatria-procesadora-portuguesa', 'Procesadora Agropatria Portuguesa', 9.043, -69.755, 'd5xqkp',
   55000000, 2010, 'Industria', 'Portuguesa', 'critica', 'MAT',
   'https://transparenciave.org/obras/agropatria-pgsa', '[]'::jsonb,
   'Complejo de procesamiento agrícola. Construido parcialmente; capacidad subutilizada.',
   45, 30, 38000000, 'Hugo Chávez Frías', 'PSUV', 'MAT + Agropatria'),

  -- Más obras estratégicas
  ('hidroelectrica-fabricio-ojeda', 'Hidroeléctrica Fabricio Ojeda (Uribante-Caparo)', 7.953, -71.776, 'd5z9kp',
   1900000000, 2005, 'Energía', 'Táchira', 'paralizada', 'CORPOELEC',
   'https://transparenciave.org/obras/uribante-caparo', '[]'::jsonb,
   'Complejo Uribante-Caparo. Solo Etapa 1 operativa; Etapas 2 y 3 anunciadas hace décadas sin avance.',
   30, 70, 1100000000, 'Hugo Chávez Frías', 'PSUV', 'EDELCA'),
  ('puerto-cabello-modernizacion', 'Puerto de Puerto Cabello (modernización)', 10.486, -68.013, 'd6r6kp',
   780000000, 2008, 'Infraestructura', 'Carabobo', 'critica', 'BoliPuertos',
   'https://transparenciave.org/obras/puerto-cabello', '[]'::jsonb,
   'Modernización del principal puerto comercial. Capacidad operativa reducida por falta de equipos y dragado.',
   55, 65, 470000000, 'Hugo Chávez Frías', 'PSUV', 'BoliPuertos'),
  ('telefericos-merida-fase2', 'Sistema Teleférico de Mérida (rehabilitación fase 2)', 8.585, -71.156, 'd66ukp',
   165000000, 2008, 'Infraestructura', 'Mérida', 'critica', 'VENTEL',
   'https://transparenciave.org/obras/teleferico-merida', '[]'::jsonb,
   'Teleférico más alto del mundo. Reinaugurado en 2016 tras 8 años de obras; algunas estaciones intermedias permanecen cerradas.',
   75, 80, 92000000, 'Hugo Chávez Frías', 'PSUV', 'VENTEL'),
  ('satelite-sucre', 'Satélite Antonio José de Sucre (VRSS-2)', 10.480, -66.910, 'djv4kp',
   140000000, 2014, 'Telecomunicaciones', 'Distrito Capital', 'inoperativa', 'ABAE',
   'https://transparenciave.org/obras/satelite-sucre', '[]'::jsonb,
   'Segundo satélite de observación. Lanzado en 2017; reportado fuera de operación desde 2020.',
   90, 0, 140000000, 'Nicolás Maduro', 'PSUV', 'CGWIC (China)'),
  ('sistema-iv-republica', 'Sistema IV República (anuncios infraestructura múltiple)', 10.480, -66.900, 'djv1kp',
   2200000000, 1999, 'Infraestructura', 'Distrito Capital', 'inoperativa', 'MPD',
   'https://transparenciave.org/obras/sistema-iv-republica', '[]'::jsonb,
   'Paquete de obras anunciadas en 1999 al inicio del gobierno chavista. Documentación pública incompleta; varias obras nunca pasaron de estudio.',
   15, 30, 1700000000, 'Hugo Chávez Frías', 'MVR', 'múltiples (sin licitación documentada)'),
  ('mision-arbol-reforestacion', 'Misión Árbol — programa nacional reforestación', 10.480, -66.904, 'djv0kp',
   85000000, 2006, 'Agricultura', 'Distrito Capital', 'critica', 'MINEC',
   'https://transparenciave.org/obras/mision-arbol', '[]'::jsonb,
   'Programa de reforestación nacional. Metas anunciadas (50M árboles) lejos de cumplirse; vivero principal subutilizado.',
   35, 20, 70000000, 'Hugo Chávez Frías', 'PSUV', 'MINEC'),
  ('centro-comercial-sambil-candelaria', 'Centro Comercial Sambil La Candelaria (intervenido)', 10.504, -66.910, 'djv4kp',
   120000000, 2008, 'Infraestructura', 'Distrito Capital', 'inoperativa', 'GOBIERNO',
   'https://transparenciave.org/obras/sambil-candelaria', '[]'::jsonb,
   'Centro comercial expropiado en 2008. Convertido en albergue por años; reactivación parcial sin completar.',
   85, 0, 120000000, 'Hugo Chávez Frías', 'PSUV', 'Constructora Sambil (expropiación)'),
  ('hospital-cardiologico-monagas', 'Hospital Cardiológico de Maturín', 9.755, -63.187, 'd71zkp',
   62000000, 2012, 'Salud', 'Monagas', 'inoperativa', 'MPPS',
   'https://transparenciave.org/obras/cardio-monagas', '[]'::jsonb,
   'Hospital especializado. Estructura levantada parcialmente; sin operación desde anuncio inicial.',
   25, 40, 44000000, 'Yelitze Santaella', 'PSUV', 'MPPS regional'),
  ('estadio-jose-perez-colmenares', 'Estadio José Pérez Colmenares (renovación)', 10.247, -67.604, 'djr8kp',
   28000000, 2014, 'Deporte', 'Aragua', 'critica', 'IND',
   'https://transparenciave.org/obras/perez-colmenares', '[]'::jsonb,
   'Renovación del estadio histórico del béisbol aragüeño. Mejoras estructurales parciales; mantenimiento deficiente.',
   60, 40, 20000000, 'Tareck El Aissami', 'PSUV', 'IND regional'),
  ('centro-rehabilitacion-zulia', 'Centro Regional Rehabilitación Integral (Zulia)', 10.640, -71.642, 'e6ku5p',
   35000000, 2011, 'Salud', 'Zulia', 'inoperativa', 'MPPS',
   'https://transparenciave.org/obras/cri-zulia', '[]'::jsonb,
   'Centro de rehabilitación para pacientes con discapacidad. Equipos adquiridos sin instalación operativa.',
   40, 25, 28000000, 'Francisco Arias Cárdenas', 'PSUV', 'MPPS'),
  ('vivienda-maracaibo-curva-molina', 'Macrocomplejo Curva de Molina (Maracaibo)', 10.620, -71.640, 'e6kr4p',
   210000000, 2013, 'Vivienda', 'Zulia', 'critica', 'MINHVI',
   'https://transparenciave.org/obras/gmvv-curva-molina', '[]'::jsonb,
   'Complejo de 4.500 viviendas. Sectores entregados sin agua corriente regular ni servicios completos.',
   65, 30, 160000000, 'Francisco Arias Cárdenas', 'PSUV', 'consorcios bolivarianos'),
  ('aeropuerto-tomas-de-heres', 'Aeropuerto Tomás de Heres (Ciudad Bolívar)', 8.122, -63.537, 'd6t4kp',
   95000000, 2010, 'Infraestructura', 'Bolívar', 'critica', 'INAC',
   'https://transparenciave.org/obras/tomas-de-heres', '[]'::jsonb,
   'Modernización del aeropuerto. Pista rehabilitada parcialmente; terminal con deterioro y servicios mínimos.',
   50, 45, 65000000, 'Francisco Rangel Gómez', 'PSUV', 'INAC regional'),
  ('parque-eolico-paraguana', 'Parque Eólico Paraguaná', 11.926, -69.880, 'eeb5kp',
   470000000, 2010, 'Energía', 'Falcón', 'critica', 'CORPOELEC',
   'https://transparenciave.org/obras/eolica-paraguana', '[]'::jsonb,
   'Parque eólico de 76 aerogeneradores. Operación reducida desde 2015 por falta de mantenimiento; aporte energético marginal.',
   85, 40, 335000000, 'Hugo Chávez Frías', 'PSUV', 'Gamesa / Iberdrola'),
  ('corredor-vial-gran-caracas', 'Corredor Vial de Gran Caracas (Bicentenario)', 10.460, -66.890, 'djv1kp',
   1100000000, 2010, 'Infraestructura', 'Distrito Capital', 'critica', 'MPPTOP',
   'https://transparenciave.org/obras/corredor-gc', '[]'::jsonb,
   'Sistema de elevados, túneles y autopistas conectando municipios. Concluido parcialmente; tramos inconclusos hace años.',
   55, 60, 690000000, 'Hugo Chávez Frías', 'PSUV', 'Consorcio Bolivariano')
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  presupuesto_usd = EXCLUDED.presupuesto_usd,
  estatus = EXCLUDED.estatus,
  updated_at = NOW();
